const ERROR_NOT_FOUND = 404;
const ERROR_BAD_REQUEST = 400;
const ERROR_CONFLICT = 409;
const ERROR_SERVER = 500;
const STATUS_CREATED = 201;

module.exports = {
  ERROR_NOT_FOUND, ERROR_BAD_REQUEST, ERROR_SERVER, STATUS_CREATED, ERROR_CONFLICT,
};
